version: '3'
services:

  ghost:
    image: ghost:${GHOST_VERSION}
    restart: always
    container_name: ${GHOST_CONTAINER_NAME}
    depends_on:
      - db
    environment:
      url: ${GHOST_URL}
      database__client: mysql
      database__connection__host: ${DB_HOST}
      database__connection__user: ${DB_USER}
      database__connection__password: ${DB_PASSWORD}
      database__connection__database: ${DB_NAME}
      mail__transport: SMTP
      mail__options__service: ${SMTP_SERVICE}
      mail__options__auth__user: ${SMTP_USER}
      mail__options__auth__pass: ${SMTP_PASSWORD}


    volumes:
      - ${GHOST_DATA}:/var/lib/ghost/content

  db:
    image: mysql:${MYSQL_VERSION}
    restart: always
    container_name: ${MYSQL_CONTAINER_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${MYSQL_DATA}:/var/lib/mysql

  nginx:
    image: nginx:${NGINX_VERSION}
    restart: always
    container_name: ${NGINX_CONTAINER_NAME}
    depends_on:
      - ghost
    ports:
      - "80:80"
      - "443:443"
    environment:
      SERVER_NAME: ${SERVER_NAME}  
      SSL_CERT: ${SSL_CERT}
      SSL_CERT_KEY: ${SSL_CERT_KEY}
      CERT_PATH: ${CERT_PATH}
    volumes:
       - ${CERT_PATH}:/etc/letsencrypt
       - ./www:/usr/share/nginx/html
       - ./nginx/conf.d:/etc/nginx/conf.d
